version: "3.9"

services:
  notifications-service:
    build: .
    container_name: notifications-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/Notifications-db}
      - MONGODB_DATABASE=Notifications-db
    networks:
      - eciexpress-network

networks:
  eciexpress-network:
    driver: bridge