name: CD - Deploy Notifications Management Backend (Dev)

on:
  push:
    branches:
      - develop
      - 'feature/**'

jobs:
  build-and-deploy:
    name: Build, Push Image, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          echo "ACR_LOGIN_SERVER = ${{ secrets.ACR_LOGIN_SERVER }}"
          IMAGE_NAME="${{ secrets.ACR_LOGIN_SERVER }}/notifications-service"
          echo "IMAGE_NAME = $IMAGE_NAME"

          GIT_TAG=${GITHUB_SHA::7}
          echo "GIT_TAG = $GIT_TAG"

          docker build -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:$GIT_TAG" .

      - name: Push Docker image to ACR
        run: |
          IMAGE_NAME=${{ secrets.ACR_LOGIN_SERVER }}/notifications-service
          GIT_TAG=${GITHUB_SHA::7}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$GIT_TAG

      - name: Deploy container to Azure Web App (DEV)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_DEV }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/notifications-service:latest